name: flutter_java_code_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter  
  
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # GetX
  get: ^4.6.6

  # UI
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1

  # Change App Package Name
  change_app_package_name: ^1.4.0

  # Logger
  sentry_flutter: ^8.12.0

  # EaseLoading
  flutter_easyloading: ^3.0.5
  
  # dialog
  panara_dialogs: ^0.1.5

  # Local Storage
  hive_flutter: ^1.1.0

  # Firebase
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0

  # OTP
  pinput: ^5.0.1

  # HTTP Client
  dio: ^5.7.0

  # Signature
  fast_rsa: ^3.7.1
  firebase_analytics: ^11.4.0

  # Geolocator & Geocoding
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  app_settings: ^5.1.1

  # Image Operation 
  image_picker: ^1.1.2
  image_cropper: ^9.0.0

  # Load More and Refresh Data
  loadmore: ^2.1.0
  pull_to_refresh: ^2.0.0

  # Cached Image
  cached_network_image: ^3.4.1

  # Slidable
  flutter_slidable: ^3.1.2
  carousel_slider: ^5.0.0

  # Device Info
  device_info_plus: ^11.2.1

  # Conditional Rendering
  flutter_conditional_rendering: ^2.1.0

  # SVG
  flutter_svg: ^2.0.17

  # Local Auth(Biometric)
  local_auth: ^2.3.0

  # dropdown
  dropdown_button2: ^2.3.9

  # intl
  intl: ^0.19.0
  easy_stepper: ^0.8.5+1

  # Skeleton Animation
  shimmer: ^3.0.0

  # For Local Storage
  hive: ^2.2.3

  # Functional Programming
  dartz: ^0.10.1

  # For Custom Console Log
  logger: ^2.5.0
  uuid: ^4.5.1
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/
    - assets/fonts/