// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2JfXJSUZAQbSBvFw4OolsFK44vUlb1wM',
    appId: '1:74662603902:web:9420ddede5377e0d9e7c2f',
    messagingSenderId: '74662603902',
    projectId: 'flutter-java-code-app',
    authDomain: 'flutter-java-code-app.firebaseapp.com',
    storageBucket: 'flutter-java-code-app.firebasestorage.app',
    measurementId: 'G-5MFELPJLGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXA7v0nZrtDOUG9UyHOymLMfo3MJ4hL0o',
    appId: '1:74662603902:android:dd3e63513b85ddb49e7c2f',
    messagingSenderId: '74662603902',
    projectId: 'flutter-java-code-app',
    storageBucket: 'flutter-java-code-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUt2kAu16Dwe0-DPXO-vS__JqzEFkv_-M',
    appId: '1:74662603902:ios:1350b008ab5a1a349e7c2f',
    messagingSenderId: '74662603902',
    projectId: 'flutter-java-code-app',
    storageBucket: 'flutter-java-code-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterJavaCodeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUt2kAu16Dwe0-DPXO-vS__JqzEFkv_-M',
    appId: '1:74662603902:ios:1350b008ab5a1a349e7c2f',
    messagingSenderId: '74662603902',
    projectId: 'flutter-java-code-app',
    storageBucket: 'flutter-java-code-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterJavaCodeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2JfXJSUZAQbSBvFw4OolsFK44vUlb1wM',
    appId: '1:74662603902:web:eef04300020a75609e7c2f',
    messagingSenderId: '74662603902',
    projectId: 'flutter-java-code-app',
    authDomain: 'flutter-java-code-app.firebaseapp.com',
    storageBucket: 'flutter-java-code-app.firebasestorage.app',
    measurementId: 'G-L5T9KYHJQP',
  );

}